"""add last_watched_second to lesson_progress

Revision ID: cb9be2478e46
Revises: 4b52aa0bc5e3
Create Date: 2026-09-18 23:46:20.892564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9be2478e46'
down_revision: Union[str, Sequence[str], None] = '4b52aa0bc5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_progress', sa.Column('last_watched_second', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_progress', 'last_watched_second')
    # ### end Alembic commands ###
